### ISSUE TITLE
Add a CLI flag for the RPC endpoint

### ISSUE THREAD

**Issue by alessandromazza98** [Keep-Reth-Strange/reth-crawler#54]
This RPC endpoint should be a CLI flag so that it can be changed at runtime
https://github.com/Keep-Reth-Strange/reth-crawler/blob/f293294bd5e34b54699291b5bc3a8592b1d5476b/bins/reth-crawler/src/crawler/listener/update_listener.rs#L45

**Comment by 0xprames** [comment]
taken care of with #60
